services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      #      MYSQL_ROOT_PASSWORD: rizwan312
      POSTGRES_USER: rizwan
      POSTGRES_PASSWORD: rizwan312
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local
